In [1]:
#Escalonamento da Base (Ajustes de Escalas)
#Essencial quando o planejamento envolve o uso de técnicas com Distância Euclidiana

<img src="- Anexos/Escalonamento.png" width="500" height="500">

In [2]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

In [3]:
df = pd.read_csv('D:/OneDrive/OneDrive - Etec Centro Paula Souza/Databases/credit_data_updated.csv')
df.columns = ['id', 'salario', 'idade', 'emprestimo', 'aprovado']

In [4]:
print(df)

          id       salario      idade   emprestimo  aprovado
0        1.0  66155.925095  59.017015  8106.532131       0.0
1        2.0  34415.153966  48.117153  6564.745018       0.0
2        3.0  57317.170063  63.108049  8020.953296       0.0
3        4.0  42709.534201  45.751972  6103.642260       0.0
4        5.0  66952.688845  18.584336  8770.099235       1.0
...      ...           ...        ...          ...       ...
1995  1996.0  59221.044874  48.518179  1926.729397       0.0
1996  1997.0  69516.127573  23.162104  3503.176156       0.0
1997  1998.0  44311.449262  28.017167  5522.786693       1.0
1998  1999.0  43756.056605  63.971796  1622.722598       0.0
1999  2000.0  69436.579552  56.152617  7378.833599       0.0

[2000 rows x 5 columns]


In [5]:
X = df.iloc[:,1:4].values
Y = df.iloc[:, 4].values

In [6]:
print(X)

[[6.61559251e+04 5.90170151e+01 8.10653213e+03]
 [3.44151540e+04 4.81171531e+01 6.56474502e+03]
 [5.73171701e+04 6.31080495e+01 8.02095330e+03]
 ...
 [4.43114493e+04 2.80171669e+01 5.52278669e+03]
 [4.37560566e+04 6.39717958e+01 1.62272260e+03]
 [6.94365796e+04 5.61526170e+01 7.37883360e+03]]


In [7]:
print(Y)

[0. 0. 0. ... 1. 0. 0.]


In [8]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [9]:
print(X)

[[ 1.45393393  1.36538005  1.20281942]
 [-0.76217555  0.54265932  0.69642695]
 [ 0.83682073  1.67417101  1.17471147]
 ...
 [-0.07122592 -0.97448606  0.35420081]
 [-0.11000289  1.73936652 -0.92675625]
 [ 1.682986    1.14917551  0.96381038]]


In [10]:
df.iloc[:,1:4] = X

In [11]:
print(df)

          id   salario     idade  emprestimo  aprovado
0        1.0  1.453934  1.365380    1.202819       0.0
1        2.0 -0.762176  0.542659    0.696427       0.0
2        3.0  0.836821  1.674171    1.174711       0.0
3        4.0 -0.183070  0.364136    0.544980       0.0
4        5.0  1.509563 -1.686475    1.420765       1.0
...      ...       ...       ...         ...       ...
1995  1996.0  0.969747  0.572929   -0.826907       0.0
1996  1997.0  1.688540 -1.340946   -0.309130       0.0
1997  1998.0 -0.071226 -0.974486    0.354201       1.0
1998  1999.0 -0.110003  1.739367   -0.926756       0.0
1999  2000.0  1.682986  1.149176    0.963810       0.0

[2000 rows x 5 columns]


In [14]:
#Aplciando as correções na Base e exportando para um arquivo .csv

In [12]:
df.to_csv('D:/OneDrive/OneDrive - Etec Centro Paula Souza/Databases/credit_data_standarted.csv', index=False);